SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATIONTYPE](
	[NO] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_NOTIFICATIONTYPE] PRIMARY KEY CLUSTERED 
(
	[NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONITORDATA]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MONITORDATA](
	[NO] [int] IDENTITY(1,1) NOT NULL,
	[SITEID] [varchar](100) NOT NULL,
	[VALUE] [float] NOT NULL,
	[UPSTREAM] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MONITORDATA] PRIMARY KEY CLUSTERED 
(
	[NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[FREQUENCY]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FREQUENCY](
	[NO] [int] IDENTITY(1,1) NOT NULL,
	[FREQUENCY_UNIT] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_FREQUENCY] PRIMARY KEY CLUSTERED 
(
	[NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATION]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[STATION](
	[STATION_ID] [nvarchar](100) NOT NULL,
	[STATION_TYPE] [char](1) NOT NULL,
	[SW_FLOW] [float] NULL,
	[SW_LEVEL] [float] NULL,
	[GW_LEVEL] [float] NULL,
	[LNG] [float] NULL,
	[LAT] [float] NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
 CONSTRAINT [PK_STATION] PRIMARY KEY CLUSTERED 
(
	[STATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER](
	[UID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[NAME] [nvarchar](100) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[STATION_UPDATE_FLAG]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATION_UPDATE_FLAG](
	[UUID] [nvarchar](130) NOT NULL,
	[STATION_ID] [nvarchar](100) NOT NULL,
	[HAS_NEW_DATA] [bit] NOT NULL,
	[UPDATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_STATION_UPDATE_FLAG] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGISTER]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGISTER](
	[NO] [bigint] IDENTITY(1,1) NOT NULL,
	[EMAIL] [varchar](100) NULL,
	[UID] [bigint] NOT NULL,
	[ROLE] [char](1) NOT NULL,
	[NOTIFICATIONTYPE_NO] [int] NOT NULL,
 CONSTRAINT [PK_REGISTER] PRIMARY KEY CLUSTERED 
(
	[NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UID of WNS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGISTER', @level2type=N'COLUMN',@level2name=N'UID'
GO
/****** Object:  Table [dbo].[REGISTER_POI]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGISTER_POI](
	[REGISTER_NO] [bigint] NOT NULL,
	[SEQ] [bigint] NOT NULL,
	[POI_TYPE] [char](1) NOT NULL,
	[STATION_ID] [nvarchar](100) NULL,
	[LNG] [float] NULL,
	[LAT] [float] NULL,
	[SW_LEVEL_THRESHOLD] [float] NULL,
	[SW_LEVEL_THRESHOLD_UNIT] [varchar](20) NULL,
	[SW_LEVEL_THRESHOLD_METRIC] [float] NULL,
	[SW_FLOW_THRESHOLD] [float] NULL,
	[SW_FLOW_THRESHOLD_UNIT] [varchar](20) NULL,
	[SW_FLOW_THRESHOLD_METRIC] [float] NULL,
	[FREQUENCY] [bigint] NOT NULL,
	[STATUS] [tinyint] NOT NULL,
	[NOTIFICATION_FLAG] [tinyint] NOT NULL,
	[ALERT_NOTIFCATION_TIME] [datetime] NULL,
	[MIN_LNG] [float] NULL,
	[MIN_LAT] [float] NULL,
	[MAX_LNG] [float] NULL,
	[MAX_LAT] [float] NULL,
 CONSTRAINT [PK_REGISTER_POI] PRIMARY KEY CLUSTERED 
(
	[REGISTER_NO] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'P : position with lnglat
S : station id' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGISTER_POI', @level2type=N'COLUMN',@level2name=N'POI_TYPE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0:Pending
1:Valid
9:Invalid' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'REGISTER_POI', @level2type=N'COLUMN',@level2name=N'STATUS'
GO
/****** Object:  Table [dbo].[REGISTER_STATION]    Script Date: 04/29/2013 16:22:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGISTER_STATION](
	[REGISTER_NO] [bigint] NOT NULL,
	[REGISTER_POI_SEQ] [bigint] NOT NULL,
	[SEQ] [bigint] NOT NULL,
	[STATION_ID] [nvarchar](100) NOT NULL,
	[UPSTREAM] [nvarchar](50) NULL,
 CONSTRAINT [PK_REGISTER_STATION] PRIMARY KEY CLUSTERED 
(
	[REGISTER_NO] ASC,
	[REGISTER_POI_SEQ] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Default [DF_STATION_UPDATE_FLAG_HAS_NEW_DATA]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[STATION_UPDATE_FLAG] ADD  CONSTRAINT [DF_STATION_UPDATE_FLAG_HAS_NEW_DATA]  DEFAULT ((0)) FOR [HAS_NEW_DATA]
GO
/****** Object:  Default [DF_REGISTER_POI_STATUS]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[REGISTER_POI] ADD  CONSTRAINT [DF_REGISTER_POI_STATUS]  DEFAULT ((0)) FOR [STATUS]
GO
/****** Object:  Default [DF_REGISTER_POI_NOTIFICATION_FLAG]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[REGISTER_POI] ADD  CONSTRAINT [DF_REGISTER_POI_NOTIFICATION_FLAG]  DEFAULT ((0)) FOR [NOTIFICATION_FLAG]
GO
/****** Object:  ForeignKey [FK_STATION_UPDATE_FLAG_STATION]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[STATION_UPDATE_FLAG]  WITH CHECK ADD  CONSTRAINT [FK_STATION_UPDATE_FLAG_STATION] FOREIGN KEY([STATION_ID])
REFERENCES [dbo].[STATION] ([STATION_ID])
GO
ALTER TABLE [dbo].[STATION_UPDATE_FLAG] CHECK CONSTRAINT [FK_STATION_UPDATE_FLAG_STATION]
GO
/****** Object:  ForeignKey [FK_REGISTER_NOTIFICATIONTYPE]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[REGISTER]  WITH CHECK ADD  CONSTRAINT [FK_REGISTER_NOTIFICATIONTYPE] FOREIGN KEY([NOTIFICATIONTYPE_NO])
REFERENCES [dbo].[NOTIFICATIONTYPE] ([NO])
GO
ALTER TABLE [dbo].[REGISTER] CHECK CONSTRAINT [FK_REGISTER_NOTIFICATIONTYPE]
GO
/****** Object:  ForeignKey [FK_REGISTER_POI_REGISTER]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[REGISTER_POI]  WITH CHECK ADD  CONSTRAINT [FK_REGISTER_POI_REGISTER] FOREIGN KEY([REGISTER_NO])
REFERENCES [dbo].[REGISTER] ([NO])
GO
ALTER TABLE [dbo].[REGISTER_POI] CHECK CONSTRAINT [FK_REGISTER_POI_REGISTER]
GO
/****** Object:  ForeignKey [FK_REGISTER_STATION_REGISTER_POI]    Script Date: 04/29/2013 16:22:08 ******/
ALTER TABLE [dbo].[REGISTER_STATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTER_STATION_REGISTER_POI] FOREIGN KEY([REGISTER_NO], [REGISTER_POI_SEQ])
REFERENCES [dbo].[REGISTER_POI] ([REGISTER_NO], [SEQ])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[REGISTER_STATION] CHECK CONSTRAINT [FK_REGISTER_STATION_REGISTER_POI]
GO
