event_list_data = [
 { 'category': 'Other',
     'f_text': 'Administration',
     'f_tooltip': 'Administration',
     'leaf': True,
     'term': 'other',
     'text': 'Administration',
     'tooltip': 'Administration',
     'value': 'admin'
 },
 { 'category': 'Safety',
     'f_text': 'Rappel de pr\xc3\xa9paration',
     'f_tooltip': 'Rappel de pr\xc3\xa9paration',
     'leaf': True,
     'term': 'other',
     'text': 'Preparedness Reminders',
     'tooltip': 'Preparedness Reminders',
     'value': 'reminder'
 },
 { 'category': 'Other',
     'f_text': 'Message test',
     'f_tooltip': 'Message test',
     'leaf': True,
     'term': 'other',
     'text': 'Test Message',
     'tooltip': 'Test Message',
     'value': 'testMessage'
 },
 { 'category': 'Other',
     'f_text': 'Autres alertes',
     'f_tooltip': 'Autres alertes',
     'leaf': True,
     'term': 'other',
     'text': 'Other',
     'tooltip': 'Other',
     'value': 'other'
 },
 { 'category': 'Security',
     'children': [{ 'category': 'Security',
         'f_text': 'Crise civile',
         'f_tooltip': 'Crise civile',
         'leaf': True,
         'term': 'ems/incident/civil/emergency',
         'text': 'Civil Emergency',
         'tooltip': 'Civil Emergency',
         'value': 'civilEmerg'
     },
               { 'category': 'Security',
                   'f_text': '\xc3\x89v\xc3\xa9nement public',
                   'f_tooltip': '\xc3\x89v\xc3\xa9nement public',
                   'leaf': True,
                   'term': 'ems/incident/civil/demonstrations',
                   'text': 'Public Event',
                   'tooltip': 'Public Event',
                   'value': 'civilEvent'
               },
               { 'category': 'Other',
                   'f_text': 'Besoin de b\xc3\xa9n\xc3\xa9voles',
                   'f_tooltip': 'Besoin de b\xc3\xa9n\xc3\xa9voles',
                   'leaf': True,
                   'term': 'ems/incident/civil/volunteerRequest',
                   'text': 'Volunteer Request',
                   'tooltip': 'Volunteer Request',
                   'value': 'volunteer'
               }],
     'cls': 'folder',
     'f_text': 'Civil',
     'f_tooltip': 'Civil',
     'term': 'ems/incident/civil',
     'text': 'Civil',
     'tooltip': 'Civil',
     'value': 'civil'
 },
 { 'category': 'Infra',
     'children': [{ 'category': 'Infra',
         'f_text': "Installations de soutien en situation d'urgence",
         'f_tooltip': "Installations de soutien en situation d'urgence",
         'leaf': True,
         'term': 'ems/incident/publicService/emergencySupportFacility',
         'text': 'Emergency Support Facilities',
         'tooltip': 'Emergency Support Facilities',
         'value': 'emergFacility'
     },
               { 'category': 'Infra',
                   'f_text': "Services de soutien d'urgence",
                   'f_tooltip': "Services de soutien d'urgence",
                   'leaf': True,
                   'term': 'ems/incident/publicService/emergencySupportService',
                   'text': 'Emergency Support Services',
                   'tooltip': 'Emergency Support Services',
                   'value': 'emergSupport'
               },
               { 'category': 'Infra',
                   'f_text': 'Autobus scolaire',
                   'f_tooltip': 'Autobus scolaire',
                   'leaf': True,
                   'term': 'ems/operations/emergency/bus',
                   'text': 'School Bus',
                   'tooltip': 'School Bus',
                   'value': 'schoolBus'
               },
               { 'category': 'Infra',
                   'f_text': "Fermeture d'\xc3\xa9cole",
                   'f_tooltip': "Fermeture d'\xc3\xa9cole",
                   'leaf': True,
                   'term': 'ems/incident/publicService/schoolClosure',
                   'text': 'School Closure',
                   'tooltip': 'School Closure',
                   'value': 'schoolClose'
               },
               { 'category': 'Infra',
                   'f_text': "Isolement d'\xc3\xa9cole",
                   'f_tooltip': "Isolement d'\xc3\xa9cole",
                   'leaf': True,
                   'term': 'ems/incident/publicService/schoolLockdown',
                   'text': 'School Lockdown',
                   'tooltip': 'School Lockdown',
                   'value': 'schoolLock'
               },
               { 'category': 'Infra',
                   'f_text': 'Service ou installation',
                   'f_tooltip': 'Service ou installation',
                   'leaf': True,
                   'term': 'ems/incident/publicService/serviceOrFacility',
                   'text': 'Service or Facility',
                   'tooltip': 'Service or Facility',
                   'value': 'facility'
               },
               { 'category': 'Infra',
                   'f_text': 'Transport public',
                   'f_tooltip': 'Transport public',
                   'leaf': True,
                   'term': 'ems/incident/publicService/transit',
                   'text': 'Transit',
                   'tooltip': 'Transit',
                   'value': 'transit'
               }],
     'cls': 'folder',
     'f_text': 'Services publics',
     'f_tooltip': 'Services publics',
     'term': 'ems/incident/publicService',
     'text': 'Public Services',
     'tooltip': 'Public Services',
     'value': 'publicServic'
 },
 { 'category': 'Security',
     'children': [{ 'category': 'Security',
         'f_text': 'Personne dangereus',
         'f_tooltip': 'Personne dangereus',
         'leaf': True,
         'term': 'ems/incident/crime/dangerousPerson',
         'text': 'Dangerous Person',
         'tooltip': 'Dangerous Person',
         'value': 'dangerPerson'
     },
               { 'category': 'Security',
                   'f_text': 'Crime contre le propri\xc3\xa9t\xc3\xa9',
                   'f_tooltip': 'Crime contre le propri\xc3\xa9t\xc3\xa9',
                   'leaf': True,
                   'term': 'ems/incident/crime/homeCrime',
                   'text': 'Home Crime',
                   'tooltip': 'Home Crime',
                   'value': 'homeCrime'
               },
               { 'category': 'Security',
                   'f_text': 'Crime industriel',
                   'f_tooltip': 'Crime industriel',
                   'leaf': True,
                   'term': 'ems/incident/crime/industrialCrime',
                   'text': 'Industrial Crime',
                   'tooltip': 'Industrial Crime',
                   'value': 'industCrime'
               },
               { 'category': 'Security',
                   'f_text': 'Crime dans les commerces',
                   'f_tooltip': 'Crime dans les commerces',
                   'leaf': True,
                   'term': 'ems/incident/crime/retailCrime',
                   'text': 'Retail Crime',
                   'tooltip': 'Retail Crime',
                   'value': 'retailCrime'
               },
               { 'category': 'Security',
                   'f_text': 'Terrorisme',
                   'f_tooltip': 'Terrorisme',
                   'leaf': True,
                   'term': 'ems/incident/crime/terrorism',
                   'text': 'Terrorism',
                   'tooltip': 'Terrorism',
                   'value': 'terrorism'
               },
               { 'category': 'Security',
                   'f_text': 'Crime de v\xc3\xa9hicule',
                   'f_tooltip': 'Crime de v\xc3\xa9hicule',
                   'leaf': True,
                   'term': 'ems/incident/crime/vehicleCrime',
                   'text': 'Vehicle Crime',
                   'tooltip': 'Vehicle Crime',
                   'value': 'vehicleCrime'
               }],
     'cls': 'folder',
     'f_text': 'Activit\xc3\xa9 criminelle',
     'f_tooltip': 'Activit\xc3\xa9 criminelle',
     'term': 'ems/incident/crime',
     'text': 'Criminal Activity',
     'tooltip': 'Criminal Activity',
     'value': 'crime'
 },
 { 'category': 'Rescue',
     'children': [{ 'category': 'Rescue',
         'f_text': 'Alerte Amber',
         'f_tooltip': 'Alerte Amber',
         'leaf': True,
         'term': 'ems/incident/missingPerson/amberAlert',
         'text': 'Amber Alert',
         'tooltip': 'Amber Alert',
         'value': 'amber'
     },
               { 'category': 'Rescue',
                   'f_text': 'Personne vuln\xc3\xa9rable disparue',
                   'f_tooltip': 'Personne vuln\xc3\xa9rable disparue',
                   'leaf': True,
                   'term': 'ems/incident/missingPerson/missingVulnerablePerson',
                   'text': 'Missing Vulnerable Person',
                   'tooltip': 'Missing Vulnerable Person',
                   'value': 'missingVulPer'
               },
               { 'category': 'Rescue',
                   'f_text': 'Alerte Silver',
                   'f_tooltip': 'Alerte Silver',
                   'leaf': True,
                   'term': 'ems/incident/missingPerson/silver',
                   'text': 'Silver Alert',
                   'tooltip': 'Silver Alert',
                   'value': 'silver'
               }],
     'cls': 'folder',
     'f_text': 'Personne manquante',
     'f_tooltip': 'Personne manquante',
     'term': 'ems/incident/missingPerson',
     'text': 'Missing Person',
     'tooltip': 'Missing Person',
     'value': 'missingPer'
 },
 { 'category': 'Rescue',
     'f_text': 'Sauvetage',
     'f_tooltip': 'Sauvetage',
     'leaf': True,
     'term': 'ems/incident/rescue',
     'text': 'Rescue',
     'tooltip': 'Rescue',
     'value': 'rescue'
 },
 { 'category': 'Transport',
     'children': [{ 'category': 'Transport',
         'f_text': 'Accident ferroviaire',
         'f_tooltip': 'Accident ferroviaire',
         'leaf': True,
         'term': 'ems/incident/railway/railwayAccident',
         'text': 'Train Accident',
         'tooltip': 'Train Accident',
         'value': 'train'
     }],
     'cls': 'folder',
     'f_text': 'Ferroviaire',
     'f_tooltip': 'Ferroviaire',
     'term': 'ems/incident/railway',
     'text': 'Railway',
     'tooltip': 'Railway',
     'value': 'railway'
 },
 { 'category': 'Transport',
     'children': [{ 'category': 'Transport',
         'f_text': 'Pont ferm\xc3\xa9',
         'f_tooltip': 'Pont ferm\xc3\xa9',
         'leaf': True,
         'term': 'ems/incident/roadway/bridgeClosure',
         'text': 'Bridge Closure',
         'tooltip': 'Bridge Closure',
         'value': 'bridgeClose'
     },
               { 'category': 'Transport',
                   'f_text': 'Fermeture de route',
                   'f_tooltip': 'Fermeture de route',
                   'leaf': True,
                   'term': 'ems/incident/roadway/roadwayClosure',
                   'text': 'Roadway Closure',
                   'tooltip': 'Roadway Closure',
                   'value': 'roadClose'
               },
               { 'category': 'Transport',
                   'f_text': 'Retard de circulation',
                   'f_tooltip': 'Retard de circulation',
                   'leaf': True,
                   'term': 'ems/incident/roadway/roadwayDelay',
                   'text': 'Roadway Delay',
                   'tooltip': 'Roadway Delay',
                   'value': 'roadDelay'
               },
               { 'category': 'Transport',
                   'f_text': 'Conditions routi\xc3\xa8res dangereuses',
                   'f_tooltip': 'Conditions routi\xc3\xa8res dangereuses',
                   'leaf': True,
                   'term': 'ems/incident/roadway/hazardousRoadConditions',
                   'text': 'Hazardous Road Conditions',
                   'tooltip': 'Hazardous Road Conditions',
                   'value': 'rdCondition'
               },
               { 'category': 'Transport',
                   'f_text': 'Rapport de circulation',
                   'f_tooltip': 'Rapport de circulation',
                   'leaf': True,
                   'term': 'ems/incident/roadway/trafficReport',
                   'text': 'Traffic Report',
                   'tooltip': 'Traffic Report',
                   'value': 'traffic'
               },
               { 'category': 'Transport',
                   'f_text': '\xc3\x89tat des routes',
                   'f_tooltip': '\xc3\x89tat des routes',
                   'leaf': True,
                   'term': 'ems/incident/roadway/roadwayUsageCondition',
                   'text': 'Roadway Usage Condition',
                   'tooltip': 'Roadway Usage Condition',
                   'value': 'roadUsage'
               },
               { 'category': 'Transport',
                   'f_text': 'Accident de voiture',
                   'f_tooltip': 'Accident de voiture',
                   'leaf': True,
                   'term': 'ems/incident/roadway/motorVehicleAccident',
                   'text': 'Motor Vehicle Accident',
                   'tooltip': 'Motor Vehicle Accident',
                   'value': 'accident'
               }],
     'cls': 'folder',
     'f_text': 'Routier',
     'f_tooltip': 'Routier',
     'term': 'ems/incident/roadway',
     'text': 'Roadway',
     'tooltip': 'Roadway',
     'value': 'road'
 },
 { 'category': 'CBRNE',
     'children': [{ 'category': 'CBRNE',
         'f_text': 'Risque chimique',
         'f_tooltip': 'Risque chimique',
         'leaf': True,
         'term': 'ems/incident/hazardousMaterial/chemicalHazard',
         'text': 'Chemical Hazard',
         'tooltip': 'Chemical Hazard',
         'value': 'chemical'
     },
               { 'category': 'CBRNE',
                   'f_text': 'Risque biologique',
                   'f_tooltip': 'Risque biologique',
                   'leaf': True,
                   'term': 'ems/incident/hazardousMaterial/biologicalHazard',
                   'text': 'Biological Hazard',
                   'tooltip': 'Biological Hazard',
                   'value': 'biological'
               },
               { 'category': 'CBRNE',
                   'f_text': 'Risque radiologique',
                   'f_tooltip': 'Risque radiologique',
                   'leaf': True,
                   'term': 'ems/incident/hazardousMaterial/radiologicalHazard',
                   'text': 'Radiological Hazard',
                   'tooltip': 'Radiological Hazard',
                   'value': 'radiological'
               },
               { 'category': 'CBRNE',
                   'f_text': "Risque d'explosion",
                   'f_tooltip': "Risque d'explosion",
                   'leaf': True,
                   'term': 'ems/incident/hazardousMaterial/explosiveHazard',
                   'text': 'Explosive Hazard',
                   'tooltip': 'Explosive Hazard',
                   'value': 'explosive'
               },
               { 'category': 'Safety',
                   'f_text': "Chute d'objets",
                   'f_tooltip': "Chute d'objets",
                   'leaf': True,
                   'term': 'ems/incident/hazardousMaterial/fallingObjectHazard',
                   'text': 'Falling Object',
                   'tooltip': 'Falling Object',
                   'value': 'fallObject'
               }],
     'cls': 'folder',
     'f_text': 'Mati\xc3\xa8res dangereuses',
     'f_tooltip': 'Mati\xc3\xa8res dangereuses',
     'term': 'ems/incident/hazardousMaterial',
     'text': 'Hazardous Materials',
     'tooltip': 'Hazardous Materials',
     'value': 'hazmat'
 },
 { 'category': 'Infra',
     'children': [{ 'category': 'Infra',
         'f_text': 'Service de c\xc3\xa2ble',
         'f_tooltip': 'Service de c\xc3\xa2ble',
         'leaf': True,
         'term': 'ems/infrastructure/communicationsAndIT',
         'text': 'Cable Service',
         'tooltip': 'Cable Service',
         'value': 'cable'
     },
               { 'category': 'Infra',
                   'f_text': 'Approvisionnement en diesel',
                   'f_tooltip': 'Approvisionnement en diesel',
                   'leaf': True,
                   'term': 'ems/infrastructure/energy/petroleumStorage',
                   'text': 'Diesel Supply',
                   'tooltip': 'Diesel Supply',
                   'value': 'diesel'
               },
               { 'category': 'Infra',
                   'f_text': "Distribution d'\xc3\xa9lectricit\xc3\xa9",
                   'f_tooltip': "Distribution d'\xc3\xa9lectricit\xc3\xa9",
                   'leaf': True,
                   'term': 'ems/infrastructure/energy',
                   'text': 'Electricity Supply',
                   'tooltip': 'Electricity Supply',
                   'value': 'electric'
               },
               { 'category': 'Infra',
                   'f_text': 'Approvisionnement en essence',
                   'f_tooltip': 'Approvisionnement en essence',
                   'leaf': True,
                   'term': 'ems/infrastructure/energy/petroleumStorage',
                   'text': 'Gasoline Supply',
                   'tooltip': 'Gasoline Supply',
                   'value': 'gasoline'
               },
               { 'category': 'Infra',
                   'f_text': 'Approvisionnement en mazout',
                   'f_tooltip': 'Approvisionnement en mazout',
                   'leaf': True,
                   'term': 'ems/infrastructure/energy/petroleumStorage',
                   'text': 'Heating Oil Supply',
                   'tooltip': 'Heating Oil Supply',
                   'value': 'heatingOil'
               },
               { 'category': 'Infra',
                   'f_text': 'Service Internet',
                   'f_tooltip': 'Service Internet',
                   'leaf': True,
                   'term': 'ems/infrastructure/communicationsAndIT/satelliteGroundStation',
                   'text': 'Internet Service',
                   'tooltip': 'Internet Service',
                   'value': 'internet'
               },
               { 'category': 'Infra',
                   'f_text': 'Approvisionnement en gaz naturel',
                   'f_tooltip': 'Approvisionnement en gaz naturel',
                   'leaf': True,
                   'term': 'ems/infrastructure/energy/gasProcessingPlant',
                   'text': 'Natural Gas Supply',
                   'tooltip': 'Natural Gas Supply',
                   'value': 'naturalGas'
               },
               { 'category': 'Infra',
                   'f_text': 'Service par satellite',
                   'f_tooltip': 'Service par satellite',
                   'leaf': True,
                   'term': 'ems/infrastructure/communicationsAndIT/satelliteGroundStation',
                   'text': 'Satellite Service',
                   'tooltip': 'Satellite Service',
                   'value': 'satellite'
               },
               { 'category': 'Infra',
                   'f_text': "R\xc3\xa9seau d'\xc3\xa9gouts",
                   'f_tooltip': "R\xc3\xa9seau d'\xc3\xa9gouts",
                   'leaf': True,
                   'term': 'ems/infrastructure/water/SewageTreatmentFacility',
                   'text': 'Sewer System',
                   'tooltip': 'Sewer System',
                   'value': 'sewer'
               },
               { 'category': 'Infra',
                   'f_text': 'Service t\xc3\xa9l\xc3\xa9phonique',
                   'f_tooltip': 'Service t\xc3\xa9l\xc3\xa9phonique',
                   'leaf': True,
                   'term': 'ems/infrastructure/communicationsAndIT/telecommunicationFacility',
                   'text': 'Telephone Service',
                   'tooltip': 'Telephone Service',
                   'value': 'telephone'
               },
               { 'category': 'Infra',
                   'f_text': 'Service 911 inop\xc3\xa9rant',
                   'f_tooltip': 'Service 911 inop\xc3\xa9rant',
                   'leaf': True,
                   'term': 'ems/infrastructure/communicationsAndIT',
                   'text': '911 Service Inoperative',
                   'tooltip': '911 Service Inoperative',
                   'value': '911Service'
               },
               { 'category': 'Infra',
                   'f_text': 'Gestion des d\xc3\xa9chets',
                   'f_tooltip': 'Gestion des d\xc3\xa9chets',
                   'leaf': True,
                   'term': 'ems/infrastructure/generalUtility',
                   'text': 'Waste Management',
                   'tooltip': 'Waste Management',
                   'value': 'waste'
               },
               { 'category': 'Infra',
                   'f_text': 'Alimentation en eau',
                   'f_tooltip': 'Alimentation en eau',
                   'leaf': True,
                   'term': 'ems/infrastructure/water',
                   'text': 'Water Supply',
                   'tooltip': 'Water Supply',
                   'value': 'water'
               }],
     'cls': 'folder',
     'f_text': 'Utilit\xc3\xa9 publique',
     'f_tooltip': 'Utilit\xc3\xa9 publique',
     'term': 'ems/infrastructure/generalUtility',
     'text': 'Utility',
     'tooltip': 'Utility',
     'value': 'utility'
 },
 { 'category': 'Health',
     'children': [{ 'category': 'Health',
         'f_text': 'Ambulance',
         'f_tooltip': 'Ambulance',
         'leaf': True,
         'term': 'ems/operations/emergencyMedical/ambulance',
         'text': 'Ambulance',
         'tooltip': 'Ambulance',
         'value': 'ambulance'
     },
               { 'category': 'Health',
                   'f_text': 'R\xc3\xa9serve de sang',
                   'f_tooltip': 'R\xc3\xa9serve de sang',
                   'leaf': True,
                   'term': 'ems/operations/emergencyMedical/bloodSupply',
                   'text': 'Blood Supply',
                   'tooltip': 'Blood Supply',
                   'value': 'bloodSupply'
               },
               { 'category': 'Health',
                   'f_text': 'Eau potable',
                   'f_tooltip': 'Eau potable',
                   'leaf': True,
                   'term': 'ems/operations/emergency/emergencyWaterDistributionCenter',
                   'text': 'Drinking Water',
                   'tooltip': 'Drinking Water',
                   'value': 'drinkingWate'
               },
               { 'category': 'Health',
                   'f_text': 'Approvisionnement en aliments et m\xc3\xa9dicaments',
                   'f_tooltip': 'Approvisionnement en aliments et m\xc3\xa9dicaments',
                   'leaf': True,
                   'term': 'ems/infrastructure/food',
                   'text': 'Food and Drug Supply',
                   'tooltip': 'Food and Drug Supply',
                   'value': 'foodSupply'
               },
               { 'category': 'Health',
                   'f_text': 'H\xc3\xb4pital',
                   'f_tooltip': 'H\xc3\xb4pital',
                   'leaf': True,
                   'term': 'ems/operations/emergencyMedical/hospital',
                   'text': 'Hospital',
                   'tooltip': 'Hospital',
                   'value': 'hospital'
               },
               { 'category': 'Health',
                   'f_text': 'Maladie infectieuse',
                   'f_tooltip': 'Maladie infectieuse',
                   'leaf': True,
                   'term': 'ems/incident/health/infectiousDisease',
                   'text': 'Infectious Disease',
                   'tooltip': 'Infectious Disease',
                   'value': 'infectious'
               }],
     'cls': 'folder',
     'f_text': 'Sant\xc3\xa9',
     'f_tooltip': 'Sant\xc3\xa9',
     'term': 'ems/incident/health',
     'text': 'Health',
     'tooltip': 'Health',
     'value': 'health'
 },
 { 'category': 'Other',
     'children': [{ 'category': 'Other',
         'f_text': 'Maladie infectieuse v\xc3\xa9g\xc3\xa9tale',
         'f_tooltip': 'Maladie infectieuse v\xc3\xa9g\xc3\xa9tale',
         'leaf': True,
         'term': 'ems/incident/plantHealth',
         'text': 'Plant Infectious Disease',
         'tooltip': 'Plant Infectious Disease',
         'value': 'plantInfect'
     }],
     'cls': 'folder',
     'f_text': 'Sant\xc3\xa9 v\xc3\xa9g\xc3\xa9tale',
     'f_tooltip': 'Sant\xc3\xa9 v\xc3\xa9g\xc3\xa9tale',
     'term': 'ems/incident/plantHealth',
     'text': 'Plant Health',
     'tooltip': 'Plant Health',
     'value': 'plant'
 },
 { 'category': 'Security',
     'f_text': 'Animal dangereux',
     'f_tooltip': 'Animal dangereux',
     'leaf': True,
     'term': 'ems/incident/dangerousAnimal',
     'text': 'Dangerous Animal',
     'tooltip': 'Dangerous Animal',
     'value': 'animalDang'
 },
 { 'category': 'Health',
     'children': [{ 'category': 'Health',
         'f_text': 'Maladie animale',
         'f_tooltip': 'Maladie animale',
         'leaf': True,
         'term': 'ems/incident/animalHealth/animalDisease',
         'text': 'Animal Disease',
         'tooltip': 'Animal Disease',
         'value': 'animalDiseas'
     },
               { 'category': 'Health',
                   'f_text': 'Nourriture animale',
                   'f_tooltip': 'Nourriture animale',
                   'leaf': True,
                   'term': 'ems/incident/animalHealth/animalFeed',
                   'text': 'Animal Feed',
                   'tooltip': 'Animal Feed',
                   'value': 'animalFeed'
               }],
     'cls': 'folder',
     'f_text': 'Sant\xc3\xa9 animale',
     'f_tooltip': 'Sant\xc3\xa9 animale',
     'term': 'ems/incident/animalHealth',
     'text': 'Animal Health',
     'tooltip': 'Animal Health',
     'value': 'animalHealth'
 },
 { 'category': 'Safety',
     'f_text': 'S\xc3\xa9curit\xc3\xa9 des produits',
     'f_tooltip': 'S\xc3\xa9curit\xc3\xa9 des produits',
     'leaf': True,
     'term': 'other',
     'text': 'Product Safety',
     'tooltip': 'Product Safety',
     'value': 'product'
 },
 { 'category': 'Env',
     'f_text': "Qualit\xc3\xa9 de l'air",
     'f_tooltip': "Qualit\xc3\xa9 de l'air",
     'leaf': True,
     'term': 'ems/incident/airQuality',
     'text': 'Air Quality',
     'tooltip': 'Air Quality',
     'value': 'airQuality'
 },
 { 'category': 'Fire',
     'children': [{ 'category': 'Fire',
         'f_text': 'Feux de brousse',
         'f_tooltip': 'Feux de brousse',
         'leaf': True,
         'term': 'ems/incident/fire/wildFire',
         'text': 'Wildfire',
         'tooltip': 'Wildfire',
         'value': 'wildfire'
     },
               { 'category': 'Fire',
                   'f_text': 'Feu industrielle',
                   'f_tooltip': 'Feu industrielle',
                   'leaf': True,
                   'term': 'ems/incident/fire/industryFire',
                   'text': 'Industrial Fire',
                   'tooltip': 'Industrial Fire',
                   'value': 'industryFire'
               },
               { 'category': 'Fire',
                   'f_text': 'Feu urbain',
                   'f_tooltip': 'Feu urbain',
                   'leaf': True,
                   'term': 'ems/incident/fire/urbanFire',
                   'text': 'Urban Fire',
                   'tooltip': 'Urban Fire',
                   'value': 'urbanFire'
               },
               { 'category': 'Fire',
                   'f_text': 'Feux de for\xc3\xaats',
                   'f_tooltip': 'Feux de for\xc3\xaats',
                   'leaf': True,
                   'term': 'ems/incident/fire/forestFire',
                   'text': 'Forest Fire',
                   'tooltip': 'Forest Fire',
                   'value': 'forestFire'
               }],
     'cls': 'folder',
     'f_text': 'Incendie',
     'f_tooltip': 'Incendie',
     'term': 'ems/incident/fire',
     'text': 'Fire',
     'tooltip': 'Fire',
     'value': 'fire'
 },
 { 'category': 'Met',
     'children': [{ 'category': 'Met',
         'f_text': 'Onde de Temp\xc3\xaate',
         'f_tooltip': 'Onde de Temp\xc3\xaate',
         'leaf': True,
         'term': 'ems/incident/flood/stormSurge',
         'text': 'Storm Surge',
         'tooltip': 'Storm Surge',
         'value': 'stormSurge'
     },
               { 'category': 'Met',
                   'f_text': 'Niveau \xc3\xa9lev\xc3\xa9 des eaux',
                   'f_tooltip': 'Niveau \xc3\xa9lev\xc3\xa9 des eaux',
                   'leaf': True,
                   'term': 'ems/incident/flood/highWater',
                   'text': 'High Water Level',
                   'tooltip': 'High Water Level',
                   'value': 'highWater'
               },
               { 'category': 'Met',
                   'f_text': 'Inondation par ruissellement de surface',
                   'f_tooltip': 'Inondation par ruissellement de surface',
                   'leaf': True,
                   'term': 'ems/incident/flood/overlandFlowFlood',
                   'text': 'Overland Flow Flood',
                   'tooltip': 'Overland Flow Flood',
                   'value': 'overflood'
               },
               { 'category': 'Safety',
                   'f_text': 'Inondation soudaine',
                   'f_tooltip': 'Inondation soudaine',
                   'leaf': True,
                   'term': 'ems/incident/flood/flashFlood',
                   'text': 'Flash Flood',
                   'tooltip': 'Flash Flood',
                   'value': 'flashFlood'
               },
               { 'category': 'Safety',
                   'f_text': 'D\xc3\xa9bordement de barrage',
                   'f_tooltip': 'D\xc3\xa9bordement de barrage',
                   'leaf': True,
                   'term': 'ems/incident/flood/damOverflow',
                   'text': 'Dam Overflow',
                   'tooltip': 'Dam Overflow',
                   'value': 'damOverflow'
               }],
     'cls': 'folder',
     'f_text': 'Inondation',
     'f_tooltip': 'Inondation',
     'term': 'ems/incident/flood',
     'text': 'Flood',
     'tooltip': 'Flood',
     'value': 'flood'
 },
 { 'category': 'Transport',
     'children': [{ 'category': 'Transport',
         'f_text': 'Avis aux navigateurs',
         'f_tooltip': 'Avis aux navigateurs',
         'leaf': True,
         'term': 'ems/incident/aviation/noticeToAirmen',
         'text': 'Notice to Airmen',
         'tooltip': 'Notice to Airmen',
         'value': 'notam'
     },
               { 'category': 'Transport',
                   'f_text': "Fermeture de l'espace a\xc3\xa9rien",
                   'f_tooltip': "Fermeture de l'espace a\xc3\xa9rien",
                   'leaf': True,
                   'term': 'ems/incident/aviation/airspaceClosure',
                   'text': 'Airspace Closure',
                   'tooltip': 'Airspace Closure',
                   'value': 'airspaceClos'
               },
               { 'category': 'Transport',
                   'f_text': "Fermeture d'a\xc3\xa9roport",
                   'f_tooltip': "Fermeture d'a\xc3\xa9roport",
                   'leaf': True,
                   'term': 'ems/incident/aviation/airportClosure',
                   'text': 'Airport Closure',
                   'tooltip': 'Airport Closure',
                   'value': 'airportClose'
               },
               { 'category': 'Transport',
                   'f_text': "Ecrasement d'avion",
                   'f_tooltip': "Ecrasement d'avion",
                   'leaf': True,
                   'term': 'ems/incident/aviation/aircraftCrash',
                   'text': 'Aircraft Crash',
                   'tooltip': 'Aircraft Crash',
                   'value': 'aircraftCras'
               }],
     'cls': 'folder',
     'f_text': 'Aviation',
     'f_tooltip': 'Aviation',
     'term': 'ems/incident/aviation',
     'text': 'Aviation',
     'tooltip': 'Aviation',
     'value': 'aviation'
 },
 { 'category': 'Geo',
     'children': [{ 'category': 'Geo',
         'f_text': 'Avalanche',
         'f_tooltip': 'Avalanche',
         'leaf': True,
         'term': 'ems/incident/geophysical/avalanche',
         'text': 'Avalanche',
         'tooltip': 'Avalanche',
         'value': 'avalanche'
     },
               { 'category': 'Geo',
                   'f_text': 'Tremblement de terre',
                   'f_tooltip': 'Tremblement de terre',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/earthquake',
                   'text': 'Earthquake',
                   'tooltip': 'Earthquake',
                   'value': 'earthquake'
               },
               { 'category': 'Geo',
                   'f_text': 'Glissement de terrain',
                   'f_tooltip': 'Glissement de terrain',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/landslide',
                   'text': 'Landslide',
                   'tooltip': 'Landslide',
                   'value': 'landslide'
               },
               { 'category': 'Geo',
                   'f_text': 'Orage magn\xc3\xa9tique',
                   'f_tooltip': 'Orage magn\xc3\xa9tique',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/magneticStorm',
                   'text': 'Magnetic Storm',
                   'tooltip': 'Magnetic Storm',
                   'value': 'magnetStorm'
               },
               { 'category': 'Geo',
                   'f_text': 'Tsunami',
                   'f_tooltip': 'Tsunami',
                   'leaf': True,
                   'term': 'ems/incident/flood/tsunami',
                   'text': 'Tsunami',
                   'tooltip': 'Tsunami',
                   'value': 'tsunami'
               },
               { 'category': 'Geo',
                   'f_text': 'M\xc3\xa9t\xc3\xa9orite',
                   'f_tooltip': 'M\xc3\xa9t\xc3\xa9orite',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/meteorite',
                   'text': 'Meteorite',
                   'tooltip': 'Meteorite',
                   'value': 'meteor'
               },
               { 'category': 'Geo',
                   'f_text': 'lahars',
                   'f_tooltip': 'lahars',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/lahar',
                   'text': 'Lahar',
                   'tooltip': 'Lahar',
                   'value': 'lahar'
               },
               { 'category': 'Geo',
                   'f_text': 'Coul\xc3\xa9es pyroclastiques',
                   'f_tooltip': 'Coul\xc3\xa9es pyroclastiques',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/pyroclasticFlow',
                   'text': 'Pyroclastic Flow',
                   'tooltip': 'Pyroclastic Flow',
                   'value': 'pyroclasticF'
               },
               { 'category': 'Geo',
                   'f_text': 'Nu\xc3\xa9es ardentes',
                   'f_tooltip': 'Nu\xc3\xa9es ardentes',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/pyroclasticSurge',
                   'text': 'Pyroclastic Surge',
                   'tooltip': 'Pyroclastic Surge',
                   'value': 'pyroclasticS'
               },
               { 'category': 'Geo',
                   'f_text': 'Nuage de cendre',
                   'f_tooltip': 'Nuage de cendre',
                   'leaf': True,
                   'term': 'ems/incident/geophysical/volcanicAshCloud',
                   'text': 'Volcanic Ash Cloud',
                   'tooltip': 'Volcanic Ash Cloud',
                   'value': 'volcanicAsh'
               }],
     'cls': 'folder',
     'f_text': 'G\xc3\xa9ophysique',
     'f_tooltip': 'G\xc3\xa9ophysique',
     'term': 'ems/incident/geophyiscal',
     'text': 'Geophysical',
     'tooltip': 'Geophysical',
     'value': 'geophyiscal'
 },
 { 'category': 'Met',
     'children': [{ 'category': 'Met',
         'f_text': 'Blizzard',
         'f_tooltip': 'Blizzard',
         'leaf': True,
         'term': 'ems/incident/meteorological/blizzard',
         'text': 'Blizzard',
         'tooltip': 'Blizzard',
         'value': 'blizzard'
     },
               { 'category': 'Met',
                   'f_text': 'Poudrerie',
                   'f_tooltip': 'Poudrerie',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/blowingSnow',
                   'text': 'Blowing Snow',
                   'tooltip': 'Blowing Snow',
                   'value': 'blowingSnow'
               },
               { 'category': 'Met',
                   'f_text': 'Temp\xc3\xaate de poussi\xc3\xa8re',
                   'f_tooltip': 'Temp\xc3\xaate de poussi\xc3\xa8re',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/dustStorm',
                   'text': 'Dust Storm',
                   'tooltip': 'Dust Storm',
                   'value': 'dustStorm'
               },
               { 'category': 'Met',
                   'f_text': 'Bruine verglacante',
                   'f_tooltip': 'Bruine verglacante',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/freezingDrizzle',
                   'text': 'Freezing Drizzle',
                   'tooltip': 'Freezing Drizzle',
                   'value': 'freezeDrzl'
               },
               { 'category': 'Met',
                   'f_text': 'Pluie verglacante',
                   'f_tooltip': 'Pluie verglacante',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/freezingRain',
                   'text': 'Freezing Rain',
                   'tooltip': 'Freezing Rain',
                   'value': 'freezeRain'
               },
               { 'category': 'Met',
                   'f_text': 'Ouragan',
                   'f_tooltip': 'Ouragan',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/hurricane',
                   'text': 'Hurricane',
                   'tooltip': 'Hurricane',
                   'value': 'hurricane'
               },
               { 'category': 'Met',
                   'f_text': 'Pluie',
                   'f_tooltip': 'Pluie',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/rainfall',
                   'text': 'Rainfall',
                   'tooltip': 'Rainfall',
                   'value': 'rainfall'
               },
               { 'category': 'Met',
                   'f_text': 'Orages',
                   'f_tooltip': 'Orages',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/thunderstorm',
                   'text': 'Thunderstorm',
                   'tooltip': 'Thunderstorm',
                   'value': 'thunderstorm'
               },
               { 'category': 'Met',
                   'f_text': 'Neige',
                   'f_tooltip': 'Neige',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/snowfall',
                   'text': 'Snowfall',
                   'tooltip': 'Snowfall',
                   'value': 'snowfall'
               },
               { 'category': 'Met',
                   'f_text': 'Bourrasque de neige',
                   'f_tooltip': 'Bourrasque de neige',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/snowSquall',
                   'text': 'Snow Squall',
                   'tooltip': 'Snow Squall',
                   'value': 'snowSquall'
               },
               { 'category': 'Met',
                   'f_text': 'Tornade',
                   'f_tooltip': 'Tornade',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/tornado',
                   'text': 'Tornado',
                   'tooltip': 'Tornado',
                   'value': 'tornado'
               },
               { 'category': 'Met',
                   'f_text': 'Temp\xc3\xaate tropicale',
                   'f_tooltip': 'Temp\xc3\xaate tropicale',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/tropicalStorm',
                   'text': 'Tropical Storm',
                   'tooltip': 'Tropical Storm',
                   'value': 'tropStorm'
               },
               { 'category': 'Met',
                   'f_text': 'Temp\xc3\xaate hivernale',
                   'f_tooltip': 'Temp\xc3\xaate hivernale',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/winterStorm',
                   'text': 'Winter Storm',
                   'tooltip': 'Winter Storm',
                   'value': 'winterStorm'
               },
               { 'category': 'Met',
                   'f_text': 'M\xc3\xa9t\xc3\xa9o',
                   'f_tooltip': 'M\xc3\xa9t\xc3\xa9o',
                   'leaf': True,
                   'term': 'ems/incident/meteorological',
                   'text': 'Weather',
                   'tooltip': 'Weather',
                   'value': 'weather'
               }],
     'cls': 'folder',
     'f_text': 'Temp\xc3\xaate',
     'f_tooltip': 'Temp\xc3\xaate',
     'term': 'ems/incident/meteorological',
     'text': 'Storm',
     'tooltip': 'Storm',
     'value': 'storm'
 },
 { 'category': 'Met',
     'children': [{ 'category': 'Met',
         'f_text': "Pouss\xc3\xa9e d'air arctique",
         'f_tooltip': "Pouss\xc3\xa9e d'air arctique",
         'leaf': True,
         'term': 'ems/incident/temperature/arcticOutflow',
         'text': 'Arctic Outflow',
         'tooltip': 'Arctic Outflow',
         'value': 'arcticOut'
     },
               { 'category': 'Met',
                   'f_text': 'Vague de froid',
                   'f_tooltip': 'Vague de froid',
                   'leaf': True,
                   'term': 'ems/incident/temperature/coldWave',
                   'text': 'Cold Wave',
                   'tooltip': 'Cold Wave',
                   'value': 'coldWave'
               },
               { 'category': 'Met',
                   'f_text': 'Refroidissement soudain',
                   'f_tooltip': 'Refroidissement soudain',
                   'leaf': True,
                   'term': 'ems/incident/temperature/flashFreeze',
                   'text': 'Flash Freeze',
                   'tooltip': 'Flash Freeze',
                   'value': 'flashFreeze'
               },
               { 'category': 'Met',
                   'f_text': 'Gel',
                   'f_tooltip': 'Gel',
                   'leaf': True,
                   'term': 'ems/incident/temperature/frost',
                   'text': 'Frost',
                   'tooltip': 'Frost',
                   'value': 'frost'
               },
               { 'category': 'Met',
                   'f_text': 'Vague de chaleur',
                   'f_tooltip': 'Vague de chaleur',
                   'leaf': True,
                   'term': 'ems/incident/temperature/heatWave',
                   'text': 'Heat Wave',
                   'tooltip': 'Heat Wave',
                   'value': 'heatWave'
               },
               { 'category': 'Met',
                   'f_text': 'Chaleur et humidit\xc3\xa9 accablantes',
                   'f_tooltip': 'Chaleur et humidit\xc3\xa9 accablantes',
                   'leaf': True,
                   'term': 'ems/incident/temperature/heatAndHumidity',
                   'text': 'High Heat and Humidity',
                   'tooltip': 'High Heat and Humidity',
                   'value': 'heatHumidity'
               },
               { 'category': 'Met',
                   'f_text': 'Refroidisse-ment \xc3\xa9olien',
                   'f_tooltip': 'Refroidisse-ment \xc3\xa9olien',
                   'leaf': True,
                   'term': 'ems/incident/temperature/windChill',
                   'text': 'Wind Chill',
                   'tooltip': 'Wind Chill',
                   'value': 'windchill'
               }],
     'cls': 'folder',
     'f_text': 'Temp\xc3\xa9rature',
     'f_tooltip': 'Temp\xc3\xa9rature',
     'term': 'ems/incident/temperature',
     'text': 'Temperature',
     'tooltip': 'Temperature',
     'value': 'temperature'
 },
 { 'category': 'Met',
     'f_text': 'Vent',
     'f_tooltip': 'Vent',
     'leaf': True,
     'term': 'ems/incident/wind',
     'text': 'Wind',
     'tooltip': 'Wind',
     'value': 'wind'
 },
 { 'category': 'Met',
     'children': [{ 'category': 'Met',
         'f_text': 'Pression des glaces',
         'f_tooltip': 'Pression des glaces',
         'leaf': True,
         'term': 'ems/incident/ice/icePressure',
         'text': 'Ice Pressure',
         'tooltip': 'Ice Pressure',
         'value': 'icePressure'
     },
               { 'category': 'Met',
                   'f_text': 'Fermeture rapide de chenaux c\xc3\xb4tiers',
                   'f_tooltip': 'Fermeture rapide de chenaux c\xc3\xb4tiers',
                   'leaf': True,
                   'term': 'ems/incident/ice/rapidCloseLead',
                   'text': 'Rapid Closing of Coastal Leads',
                   'tooltip': 'Rapid Closing of Coastal Leads',
                   'value': 'rpdCloseLead'
               },
               { 'category': 'Met',
                   'f_text': 'Sp\xc3\xa9cial des glaces',
                   'f_tooltip': 'Sp\xc3\xa9cial des glaces',
                   'leaf': True,
                   'term': 'ems/incident/ice/specialIce',
                   'text': 'Special Ice',
                   'tooltip': 'Special Ice',
                   'value': 'spclIce'
               }],
     'cls': 'folder',
     'f_text': 'Glaces',
     'f_tooltip': 'Glaces',
     'term': 'ems/incident/ice',
     'text': 'Ice',
     'tooltip': 'Ice',
     'value': 'ice'
 },
 { 'category': 'Transport',
     'children': [{ 'category': 'Met',
         'f_text': 'Embruns verglacants',
         'f_tooltip': 'Embruns verglacants',
         'leaf': True,
         'term': 'ems/incident/meteorological/freezingSpray',
         'text': 'Freezing Spray',
         'tooltip': 'Freezing Spray',
         'value': 'freezngSpray'
     },
               { 'category': 'Met',
                   'f_text': 'Coups de vent',
                   'f_tooltip': 'Coups de vent',
                   'leaf': True,
                   'term': 'ems/incident/wind/galeWind',
                   'text': 'Gale Wind',
                   'tooltip': 'Gale Wind',
                   'value': 'galeWind'
               },
               { 'category': 'Met',
                   'f_text': 'Vent de force ouragan',
                   'f_tooltip': 'Vent de force ouragan',
                   'leaf': True,
                   'term': 'ems/incident/wind/hurricaneForceWind',
                   'text': 'Hurricane Force Wind',
                   'tooltip': 'Hurricane Force Wind',
                   'value': 'hurricFrcWnd'
               },
               { 'category': 'Transport',
                   'f_text': 'Iceberg',
                   'f_tooltip': 'Iceberg',
                   'leaf': True,
                   'term': 'ems/incident/ice/iceberg',
                   'text': 'Iceberg',
                   'tooltip': 'Iceberg',
                   'value': 'iceberg'
               },
               { 'category': 'Transport',
                   'f_text': 'S\xc3\xa9curit\xc3\xa9 maritime',
                   'f_tooltip': 'S\xc3\xa9curit\xc3\xa9 maritime',
                   'leaf': True,
                   'term': 'ems/incident/marine/marineSecurity',
                   'text': 'Marine Security',
                   'tooltip': 'Marine Security',
                   'value': 'marineSecure'
               },
               { 'category': 'Transport',
                   'f_text': 'Incident nautique',
                   'f_tooltip': 'Incident nautique',
                   'leaf': True,
                   'term': 'ems/incident/marine/nauticalAccident',
                   'text': 'Nautical Incident',
                   'tooltip': 'Nautical Incident',
                   'value': 'nautical'
               },
               { 'category': 'Met',
                   'f_text': 'Maritime speciale',
                   'f_tooltip': 'Maritime speciale',
                   'leaf': True,
                   'term': 'ems/incident/marine/specialMarine',
                   'text': 'Special Marine',
                   'tooltip': 'Special Marine',
                   'value': 'spclMarine'
               },
               { 'category': 'Met',
                   'f_text': 'Grains',
                   'f_tooltip': 'Grains',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/squall',
                   'text': 'Squall',
                   'tooltip': 'Squall',
                   'value': 'squall'
               },
               { 'category': 'Met',
                   'f_text': 'Vent de temp\xc3\xaate',
                   'f_tooltip': 'Vent de temp\xc3\xaate',
                   'leaf': True,
                   'term': 'ems/incident/wind/stormForceWind',
                   'text': 'Storm Force Wind',
                   'tooltip': 'Storm Force Wind',
                   'value': 'stormFrcWnd'
               },
               { 'category': 'Met',
                   'f_text': 'Vent fort',
                   'f_tooltip': 'Vent fort',
                   'leaf': True,
                   'term': 'ems/incident/wind/strongWind',
                   'text': 'Strong Wind',
                   'tooltip': 'Strong Wind',
                   'value': 'strongWind'
               },
               { 'category': 'Met',
                   'f_text': 'Trombe marine',
                   'f_tooltip': 'Trombe marine',
                   'leaf': True,
                   'term': 'ems/incident/meteorological/waterspout',
                   'text': 'Waterspout',
                   'tooltip': 'Waterspout',
                   'value': 'waterspout'
               }],
     'cls': 'folder',
     'f_text': 'Maritime',
     'f_tooltip': 'Maritime',
     'term': 'ems/incident/marine',
     'text': 'Marine',
     'tooltip': 'Marine',
     'value': 'marine'
 },
];
